services:
  php:
    container_name: php_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./docker/dev/php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - ./docker/dev/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app_network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fgbdwDX6ctRLsmO0EVjO
      MYSQL_DATABASE: infosys3
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Alcohol99%
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb/db:/var/lib/mysql
#      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
#      DATABASE_URL: "mysql://app:Alcohol99%@mariadb-db:3306/infosys3"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php

# Composer Service für Dependency Management
#  composer:
#    image: composer:latest
#    container_name: composer_deps
#    working_dir: /var/www/html
#    volumes:
#      - ./app/src:/var/www/html
#    command: composer install --ignore-platform-reqs
#    networks:
#      - app_network

# PHPUnit Test Service
#  phpunit:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: phpunit_tests
#    working_dir: /var/www/html
#    volumes:
#      - ./app/src:/var/www/html
#    command: ["./vendor/bin/phpunit", "--configuration", "phpunit.xml"]
#    networks:
#      - app_network
#    depends_on:
#      - mariadb
#    profiles:
#      - testing

networks:
  app_network:
    driver: bridge
#        external: true
